Repository unhappy1030/BloodStore, pull requests merged in 2024-01, with the labels that each got.

#31 Feat/#30
  BloodStore/Assets/Scenes/Test.unity
  BloodStore/Assets/Scripts/LeeUlim/ColliderTest.cs
  BloodStore/Assets/Scripts/LeeUlim/ColliderTest.cs.meta
Labels: feat

#33 Feat/#32
  BloodStore/Assets/Scenes/Edit.unity
  BloodStore/Assets/Scenes/Start.unity
  BloodStore/Assets/Scripts/LeeUlim/Control/ButtonControl.cs
  BloodStore/Assets/Scripts/LeeUlim/Control/GameManager.cs
  BloodStore/Assets/Scripts/LeeUlim/Control/MoneyControl.cs
  BloodStore/Assets/Scripts/LeeUlim/Control/MoneyControl.cs.meta
  BloodStore/Assets/Scripts/LeeUlim/Control/UIControl.cs
  BloodStore/Assets/Scripts/LeeUlim/Dialogue/YarnControl.cs
  BloodStore/Assets/YarnSpinner/Customer/CustomerDialogue.yarn
Labels: feat

#43 [fix] <Test> : assign script in GameManager not each script
  BloodStore/Assets/Scenes/Edit.unity
  BloodStore/Assets/Scenes/Test.unity
  BloodStore/Assets/Scripts/LeeUlim/Control/GameManager.cs
  BloodStore/Assets/Scripts/LeeUlim/Control/MouseRayCast.cs
  BloodStore/Assets/Scripts/LeeUlim/Dialogue/NPCInteract.cs
  BloodStore/Assets/Scripts/LeeUlim/Dialogue/YarnControl.cs
Labels: fix

#54 [feat] <NewFamilyTreeTest> : Add Collider create, on/off Method
  BloodStore/Assets/Prefab/NewEmpty.prefab
  BloodStore/Assets/Scripts/LeeHyangWoo/NewFamilyTree/FamilyTree/EmptyDisplay.cs
  BloodStore/Assets/Scripts/LeeHyangWoo/NewFamilyTree/FamilyTree/Group.cs
  BloodStore/Assets/Scripts/LeeHyangWoo/NewFamilyTree/FamilyTree/NodeDisplay.cs
Labels: fix

#57 Refactor/#48
  BloodStore/Assets/Prefab/Card.prefab
  BloodStore/Assets/Prefab/EmptyNode.prefab
  BloodStore/Assets/Prefab/NewNode.prefab
  BloodStore/Assets/Scenes/Edit.unity
  BloodStore/Assets/Scenes/Start.unity
  BloodStore/Assets/Scripts/LeeHyangWoo/NewFamilyTree/FamilyTree/TreeManager.cs
  BloodStore/Assets/Scripts/LeeUlim/Control/MouseRayCast.cs
  BloodStore/Assets/Scripts/LeeUlim/NodeInteraction.cs
  BloodStore/Assets/Scripts/LeeUlim/NodeInteraction.cs.meta
  BloodStore/ProjectSettings/EditorBuildSettings.asset
  BloodStore/ProjectSettings/TagManager.asset
Labels: refactor

#60 Refactor/#49
  BloodStore/Assets/Scenes/Start.unity
  BloodStore/Assets/Scripts/LeeHyangWoo/NewFamilyTree/Camera/SetCameraTarget.cs
  BloodStore/Assets/Scripts/LeeHyangWoo/NewFamilyTree/FamilyTree/Group.cs
  BloodStore/Assets/Scripts/LeeUlim/Control/CameraControl.cs
  BloodStore/Assets/Scripts/LeeUlim/Control/GameManager.cs
  BloodStore/Assets/Scripts/LeeUlim/Control/InteractObjInfo.cs
  BloodStore/Assets/Scripts/LeeUlim/Inspector/InteractObjInfoInspector.cs
  BloodStore/Assets/Scripts/LeeUlim/NodeInteraction.cs
Labels: refactor

#67 Feat/#62
  BloodStore/Assets/Prefab/NewEmpty.prefab
  BloodStore/Assets/Scenes/Edit.unity
  BloodStore/Assets/Scenes/Start.unity
  BloodStore/Assets/Scenes/Store.unity
  BloodStore/Assets/Scripts/LeeHyangWoo/NewFamilyTree/FamilyTree/EmptyDisplay.cs
  BloodStore/Assets/Scripts/LeeUlim/Control/MouseRayCast.cs
  BloodStore/Assets/Scripts/LeeUlim/NodeInteraction.cs
  BloodStore/Assets/YarnSpinner/Customer/CustomerDialogue.yarn
Labels: feat

#73 [fix] : InteractObjInfo - fix problem and checked
  BloodStore/Assets/Scenes/Start.unity
  BloodStore/Assets/Scripts/LeeUlim/Inspector/InteractObjInfoInspector.cs
Labels: fix

#81 Feat/#80
  BloodStore/Assets/Scenes/Start.unity
  BloodStore/Assets/Scenes/Store.unity
  BloodStore/Assets/Scripts/LeeUlim/Control/GameManager.cs
  BloodStore/Assets/Scripts/LeeUlim/Control/InteractObjInfo.cs
  BloodStore/Assets/Scripts/LeeUlim/Control/MouseRayCast.cs
  BloodStore/Assets/Scripts/LeeUlim/Dialogue/NPCInteract.cs
  BloodStore/Assets/Scripts/LeeUlim/Dialogue/YarnControl.cs
  BloodStore/Assets/YarnSpinner/Customer/CustomerDialogue.yarn
  BloodStore/ProjectSettings/EditorBuildSettings.asset
Labels: feat

#87 [fix] : NPCInteract - add EnableNodeCollider method at ShowTotal and …
  BloodStore/Assets/Scripts/LeeUlim/NodeInteraction.cs
  BloodStore/Assets/testRightFuture.json
Labels: fix

#90 Enhance/#88
  BloodStore/Assets/Scripts/LeeUlim/NodeInteraction.cs
Labels: enhance

#97 Feat/#91
  BloodStore/Assets/BloodPack.json
  BloodStore/Assets/Scenes/Start.unity
  BloodStore/Assets/Scenes/Store.unity
  BloodStore/Assets/Scripts/LeeUlim/Control/GameManager.cs
  BloodStore/Assets/Scripts/LeeUlim/Dialogue/DialogueControl.cs
  BloodStore/Assets/Scripts/LeeUlim/Dialogue/DialogueControl.cs.meta
  BloodStore/Assets/Scripts/LeeUlim/Dialogue/NPCInfo.cs
  BloodStore/Assets/Scripts/LeeUlim/Dialogue/NPCInteract.cs
  BloodStore/Assets/Scripts/LeeUlim/Dialogue/NPCSO.cs
  BloodStore/Assets/Scripts/LeeUlim/Dialogue/NPCSO.cs.meta
  BloodStore/Assets/Scripts/LeeUlim/Dialogue/NormalNPCSO.cs
  BloodStore/Assets/Scripts/LeeUlim/Dialogue/NormalNPCSO.cs.meta
  BloodStore/Assets/Scripts/LeeUlim/Dialogue/SOTest.meta
  BloodStore/Assets/Scripts/LeeUlim/Dialogue/SOTest/NPC.meta
  BloodStore/Assets/Scripts/LeeUlim/Dialogue/SOTest/NPC/NPC1.asset
  BloodStore/Assets/Scripts/LeeUlim/Dialogue/SOTest/NPC/NPC1.asset.meta
  BloodStore/Assets/Scripts/LeeUlim/Dialogue/SOTest/NPC/NPC1SO.asset
  BloodStore/Assets/Scripts/LeeUlim/Dialogue/SOTest/NPC/NPC1SO.asset.meta
  BloodStore/Assets/Scripts/LeeUlim/Dialogue/SOTest/NPC/NPC2.asset
  BloodStore/Assets/Scripts/LeeUlim/Dialogue/SOTest/NPC/NPC2.asset.meta
  BloodStore/Assets/Scripts/LeeUlim/Dialogue/SOTest/NPC/NPC2SO.asset
  BloodStore/Assets/Scripts/LeeUlim/Dialogue/SOTest/NPC/NPC2SO.asset.meta
  BloodStore/Assets/Scripts/LeeUlim/Dialogue/SOTest/NPC/NPC3.asset
  BloodStore/Assets/Scripts/LeeUlim/Dialogue/SOTest/NPC/NPC3.asset.meta
  BloodStore/Assets/Scripts/LeeUlim/Dialogue/SOTest/NPC/NPC3SO.asset
  BloodStore/Assets/Scripts/LeeUlim/Dialogue/SOTest/NPC/NPC3SO.asset.meta
  BloodStore/Assets/Scripts/LeeUlim/Dialogue/SOTest/NormalNPCSO.asset
  BloodStore/Assets/Scripts/LeeUlim/Dialogue/SOTest/NormalNPCSO.asset.meta
  BloodStore/Assets/Scripts/LeeUlim/Dialogue/YarnControl.cs
  BloodStore/Assets/Sprite/NoColorInteract.png
  BloodStore/Assets/Sprite/NoColorInteract.png.meta
  BloodStore/Assets/Sprite/human1.png
  BloodStore/Assets/Sprite/human1.png.meta
  BloodStore/Assets/Sprite/human2.png
  BloodStore/Assets/Sprite/human2.png.meta
  BloodStore/Assets/Sprite/vampire1.png
  BloodStore/Assets/Sprite/vampire1.png.meta
  BloodStore/Assets/YarnSpinner/Customer/CustomerDialogue.yarn
  BloodStore/Assets/YarnSpinner/Customer/test.meta
  BloodStore/Assets/YarnSpinner/Customer/test/CustomerDialogue.yarn
  BloodStore/Assets/YarnSpinner/Customer/test/CustomerDialogue.yarn.meta
  BloodStore/Assets/YarnSpinner/Customer/test/NewProject.yarnproject
  BloodStore/Assets/YarnSpinner/Customer/test/NewProject.yarnproject.meta
  BloodStore/Assets/YarnSpinner/Customer/test/Npc.meta
  BloodStore/Assets/YarnSpinner/Customer/test/Npc/NormalNPC.yarn
  BloodStore/Assets/YarnSpinner/Customer/test/Npc/NormalNPC.yarn.meta
  BloodStore/Assets/YarnSpinner/Customer/test/Npc/Npc1.yarn
  BloodStore/Assets/YarnSpinner/Customer/test/Npc/Npc1.yarn.meta
  BloodStore/Assets/YarnSpinner/Customer/test/Npc/Npc2.yarn
  BloodStore/Assets/YarnSpinner/Customer/test/Npc/Npc2.yarn.meta
  BloodStore/Assets/YarnSpinner/Customer/test/Npc/Npc3.yarn
  BloodStore/Assets/YarnSpinner/Customer/test/Npc/Npc3.yarn.meta
  BloodStore/Assets/YarnSpinner/Customer/test/ScretDiary1.yarn
  BloodStore/Assets/YarnSpinner/Customer/test/ScretDiary1.yarn.meta
Labels: feat

#102 Enhance/#99
  BloodStore/Assets/BloodPack.json
  BloodStore/Assets/Editor/InteractObjInfoInspector.cs
  BloodStore/Assets/Prefab/NewEmpty.prefab
  BloodStore/Assets/Prefab/NewNode.prefab
  BloodStore/Assets/Scenes/Start.unity
  BloodStore/Assets/Scripts/LeeUlim/Control/GameManager.cs
  BloodStore/Assets/Scripts/LeeUlim/Control/InteractObjInfo.cs
  BloodStore/Assets/Scripts/LeeUlim/Control/MouseRayCast.cs
  BloodStore/Assets/Scripts/LeeUlim/Dialogue/NPCInteract.cs
  BloodStore/Assets/Scripts/LeeUlim/NodeInteraction.cs
Labels: enhance

#109 Enhance/#106
  BloodStore/Assets/Scripts/LeeUlim/NodeInteraction.cs
Labels: enhance

#110 Feat/#98
  BloodStore/Assets/Scripts/LeeUlim/Dialogue/BloodTasteSO.cs
  BloodStore/Assets/Scripts/LeeUlim/Dialogue/BloodTasteSO.cs.meta
  BloodStore/Assets/Scripts/LeeUlim/Dialogue/DialogueControl.cs
  BloodStore/Assets/Scripts/LeeUlim/Dialogue/SOTest/Taste.meta
  BloodStore/Assets/Scripts/LeeUlim/Dialogue/SOTest/Taste/A.asset
  BloodStore/Assets/Scripts/LeeUlim/Dialogue/SOTest/Taste/A.asset.meta
  BloodStore/Assets/Scripts/LeeUlim/Dialogue/SOTest/Taste/Rh.asset
  BloodStore/Assets/Scripts/LeeUlim/Dialogue/SOTest/Taste/Rh.asset.meta
  BloodStore/Assets/Scripts/LeeUlim/Dialogue/YarnControl.cs
Labels: enhance

#114 Enhance/#106
  BloodStore/Assets/BloodPack.json
  BloodStore/Assets/FamilyTree.json
  BloodStore/Assets/Scenes/Edit.unity
  BloodStore/Assets/Scenes/Start.unity
  BloodStore/Assets/Scripts/LeeUlim/Control/CameraControl.cs
  BloodStore/Assets/Scripts/LeeUlim/NodeInteraction.cs
  BloodStore/ProjectSettings/ProjectSettings.asset
Labels: enhance
