Repository unhappy1030/BloodStore, pull requests merged in 2024-03, with the labels that each got.

#320 [feat] <FamilyTree> Prefab Node : Seperated Image By Sex
  BloodStore/Assets/Prefab/Node.prefab
  BloodStore/Assets/Scripts/FamilyTree/RamdomImage/SeperateImage.cs
  BloodStore/Assets/Scripts/FamilyTree/RamdomImage/SeperateImage.cs.meta
Labels: feat

#322 Feat/#321
  BloodStore/Assets/Prefab/Node.prefab
  BloodStore/Assets/Scenes/Start.unity
  BloodStore/Assets/Scripts/FamilyTree/EmptyDisplay.cs
  BloodStore/Assets/Scripts/FamilyTree/Group.cs
  BloodStore/Assets/Scripts/GameManager/GameManager.cs
  BloodStore/Assets/Scripts/GameManager/ImageLoad.cs
  BloodStore/Assets/Scripts/GameManager/ImageLoad.cs.meta
  BloodStore/Assets/Scripts/GameManager/Pairs.cs
  BloodStore/Assets/Scripts/SO/FamilyTreeSO/FemaleProfileImageSO.asset
  BloodStore/Assets/Scripts/SO/FamilyTreeSO/FemaleProfileImageSO.asset.meta
  BloodStore/Assets/Scripts/SO/FamilyTreeSO/MaleProfileImageSO.asset
  BloodStore/Assets/Scripts/SO/FamilyTreeSO/MaleProfileImageSO.asset.meta
  BloodStore/Assets/Scripts/SO/FamilyTreeSO/NodeSO.cs
  BloodStore/Assets/Scripts/SO/FamilyTreeSO/NodeSo.asset
  BloodStore/Assets/Scripts/SO/FamilyTreeSO/ProfileImageSO.cs
  BloodStore/Assets/Scripts/SO/FamilyTreeSO/ProfileImageSO.cs.meta
  BloodStore/Assets/Scripts/SO/FamilyTreeSO/SelectableCardSO.cs
  BloodStore/Assets/Scripts/UI/SelectableCardUI/SelectableCardDisplay.cs
  BloodStore/Assets/Scripts/UI/SelectableCardUI/SelectedCardDisplay.cs
Labels: feat

#325 [fix] : BloodSellProcess - add collider enable or disable part at Sta…
  BloodStore/Assets/Scripts/NPC/BloodSellProcess.cs
Labels: fix

#327 Enhance/#326
  BloodStore/Assets/Scripts/FamilyTree/NodeInteraction.cs
  BloodStore/Assets/Scripts/GameManager/GameManager.cs
  BloodStore/Assets/Scripts/GameManager/Tutorial.cs
  BloodStore/Assets/Scripts/NPC/NPCInteract.cs
  BloodStore/Assets/Scripts/UI/LoadStatus/LoadStatus.cs
  BloodStore/Assets/Scripts/UI/ResultFamilyTree/ResultMoney.cs
  BloodStore/Assets/Scripts/UI/ResultStoreUI/ResultStore.cs
  BloodStore/Assets/Scripts/UI/StartSceneUI/StartScene.cs
Labels: enhance

#328 Enhance/#323 1
  BloodStore/Assets/Scenes/FamilyTree.unity
  BloodStore/Assets/Scripts/FamilyTree/NodeInteraction.cs
  BloodStore/Assets/Scripts/GameManager/GameManager.cs
  BloodStore/Assets/Scripts/GameManager/Tutorial.cs
  BloodStore/Assets/Scripts/NPC/BloodSellProcess.cs
  BloodStore/Assets/Scripts/NPC/NPCInteract.cs
  BloodStore/Assets/Scripts/UI/LoadStatus/LoadStatus.cs
  BloodStore/Assets/Scripts/UI/PackingUI/PackingUI.cs
  BloodStore/Assets/Scripts/UI/ResultFamilyTree/ResultMoney.cs
  BloodStore/Assets/Scripts/UI/ResultStoreUI/ResultStore.cs
  BloodStore/Assets/Scripts/UI/StartSceneUI/StartScene.cs
Labels: enhance

#329 Enhance/#323
  BloodStore/Assets/Scenes/FamilyTree.unity
  BloodStore/Assets/Scenes/Start.unity
  BloodStore/Assets/Scripts/UI/PackingUI/PackingUI.cs
Labels: enhance

#331 [enhance] PackingUI.cs : TMP text Modified
  BloodStore/Assets/Scripts/UI/PackingUI/PackingUI.cs
Labels: enhance

#333 [enhance] NodeInteraction.cs : Add new Method SetFirstGroup not Applied
  BloodStore/Assets/Scripts/FamilyTree/NodeInteraction.cs
Labels: enhance

#340 Enhance/#336
  BloodStore/Assets/YarnSpinner/Customer/test/Npc/NormalNPC.yarn
Labels: enhance

#341 Feat/#339
  BloodStore/Assets/Animation/Animation/MoneyText.anim
  BloodStore/Assets/Animation/Animation/MoneyText.anim.meta
  BloodStore/Assets/Animation/Animation/RatingText.anim
  BloodStore/Assets/Animation/Animation/RatingText.anim.meta
  BloodStore/Assets/Animation/Animator/MoneyText.controller
  BloodStore/Assets/Animation/Animator/MoneyText.controller.meta
  BloodStore/Assets/Animation/Animator/RatingText.controller
  BloodStore/Assets/Animation/Animator/RatingText.controller.meta
  BloodStore/Assets/Scenes/Start.unity
  BloodStore/Assets/Scenes/Store.unity
  BloodStore/Assets/Scripts/GameManager/MoneyControl.cs
  BloodStore/Assets/Scripts/NPC/NPCInteract.cs
  BloodStore/Assets/Scripts/UI/MoneyUI.meta
  BloodStore/Assets/Scripts/UI/MoneyUI/MoneyUI.cs
  BloodStore/Assets/Scripts/UI/MoneyUI/MoneyUI.cs.meta
  BloodStore/Assets/Scripts/UI/StoreCanvasUI/RatingTextControl.cs
  BloodStore/Assets/Scripts/UI/StoreCanvasUI/RatingTextControl.cs.meta
Labels: feat

#342 [enhance] <FamilyTree> NodeInteraction.cs : Apply SetFirstGroup method
  BloodStore/Assets/Scripts/FamilyTree/NodeInteraction.cs
Labels: enhance

#346 Style/#345
  BloodStore/Assets/Prefab/Node.prefab
  BloodStore/Assets/Scenes/FamilyTree.unity
  BloodStore/Assets/Scripts/GameManager/ImageLoad.cs
  BloodStore/Assets/Scripts/UI/SelectableCardUI/SelectableCardDisplay.cs
  BloodStore/Assets/Sprite/svg/AddChildUI.svg.meta
Labels: style

#347 Style/#343
  BloodStore/Assets/Scenes/Store.unity
  BloodStore/Assets/Scripts/GameManager/GameManager.cs
  BloodStore/Assets/Scripts/GameManager/MouseRayCast.cs
  BloodStore/Assets/Scripts/NPC/YarnControl.cs
  BloodStore/Assets/Sprite/svg/Charactor1.svg
  BloodStore/Assets/Sprite/svg/Charactor1.svg.meta
  BloodStore/Assets/Sprite/svg/add child_noBackground.svg
  BloodStore/Assets/Sprite/svg/add child_noBackground.svg.meta
  BloodStore/Assets/Sprite/svg/button_black.svg
  BloodStore/Assets/Sprite/svg/button_black.svg.meta
  BloodStore/Assets/Sprite/svg/button_select_filled.svg
  BloodStore/Assets/Sprite/svg/button_select_filled.svg.meta
  BloodStore/Assets/Sprite/svg/charactor2.svg
  BloodStore/Assets/Sprite/svg/charactor2.svg.meta
  BloodStore/Assets/Sprite/svg/dialoguePannel.svg
  BloodStore/Assets/Sprite/svg/dialoguePannel.svg.meta
  BloodStore/Assets/Sprite/svg/saveFile.svg
  BloodStore/Assets/Sprite/svg/saveFile.svg.meta
  BloodStore/Assets/Sprite/svg/start management_btn.svg
  BloodStore/Assets/Sprite/svg/start management_btn.svg.meta
  BloodStore/Assets/Sprite/svg/ui_arrow.svg
  BloodStore/Assets/Sprite/svg/ui_arrow.svg.meta
  BloodStore/Assets/Sprite/svg/ui_arrow_Left.svg
  BloodStore/Assets/Sprite/svg/ui_arrow_Left.svg.meta
  BloodStore/Assets/Sprite/svg/ui_backgound_sqaure.svg
  BloodStore/Assets/Sprite/svg/ui_backgound_sqaure.svg.meta
  BloodStore/Assets/Sprite/svg/ui_bat.svg
  BloodStore/Assets/Sprite/svg/ui_bat.svg.meta
  BloodStore/Assets/Sprite/svg/ui_button_blank.svg
  BloodStore/Assets/Sprite/svg/ui_button_blank.svg.meta
  BloodStore/Assets/Sprite/svg/ui_money.svg
  BloodStore/Assets/Sprite/svg/ui_money.svg.meta
  BloodStore/Assets/Sprite/svg/ui_paper.svg
  BloodStore/Assets/Sprite/svg/ui_paper.svg.meta
  BloodStore/Assets/Sprite/svg/ui_subtitle.svg
  BloodStore/Assets/Sprite/svg/ui_subtitle.svg.meta
  BloodStore/Assets/Sprite/svg/ui_title2.svg
  BloodStore/Assets/Sprite/svg/ui_title2.svg.meta
  BloodStore/Assets/YarnSpinner/Customer/test/Npc/NormalNPC.yarn
Labels: style

#349 for upload
  BloodStore/Assets/Scenes/ResultFamilyTree.unity
  BloodStore/Assets/Sprite/PT_temp/Store.png
  BloodStore/Assets/Sprite/PT_temp/Store.png.meta
  BloodStore/Assets/Sprite/PT_temp/frame_blood.png
  BloodStore/Assets/Sprite/PT_temp/frame_blood.png.meta
  BloodStore/Assets/Sprite/PT_temp/frame_normal.png
  BloodStore/Assets/Sprite/PT_temp/frame_normal.png.meta
  BloodStore/Assets/Sprite/PT_temp/frame_null.png
  BloodStore/Assets/Sprite/PT_temp/frame_null.png.meta
  BloodStore/Assets/Sprite/PT_temp/frame_select.png
  BloodStore/Assets/Sprite/PT_temp/frame_select.png.meta
  BloodStore/Assets/Sprite/PT_temp/kitchen.png
  BloodStore/Assets/Sprite/PT_temp/kitchen.png.meta
  BloodStore/Assets/Sprite/PT_temp/resultFT.png
  BloodStore/Assets/Sprite/PT_temp/resultFT.png.meta
  BloodStore/Assets/Sprite/PT_temp/resultST.png
  BloodStore/Assets/Sprite/PT_temp/resultST.png.meta
  BloodStore/Assets/Sprite/PT_temp/selectCardUI_background.png
  BloodStore/Assets/Sprite/PT_temp/selectCardUI_background.png.meta
  BloodStore/Assets/Sprite/PT_temp/selectCardUI_frame1.png
  BloodStore/Assets/Sprite/PT_temp/selectCardUI_frame1.png.meta
  BloodStore/Assets/Sprite/PT_temp/selectCardUI_frame2.png
  BloodStore/Assets/Sprite/PT_temp/selectCardUI_frame2.png.meta
  BloodStore/Assets/Sprite/PT_temp/selectCardUI_frame3.png
  BloodStore/Assets/Sprite/PT_temp/selectCardUI_frame3.png.meta
  BloodStore/Assets/Sprite/PT_temp/selectCardUI_frame4.png
  BloodStore/Assets/Sprite/PT_temp/selectCardUI_frame4.png.meta
  BloodStore/Assets/Sprite/PT_temp/selectCardUI_frame5.png
  BloodStore/Assets/Sprite/PT_temp/selectCardUI_frame5.png.meta
  BloodStore/Assets/Sprite/PT_temp/selectCardUI_sealingwax.png
  BloodStore/Assets/Sprite/PT_temp/selectCardUI_sealingwax.png.meta
Labels: style

#351 Style/#343
  BloodStore/Assets/Scenes/Store.unity
  BloodStore/Assets/Scripts/NPC/BloodSellProcess.cs
  BloodStore/Assets/Sprite/PT_temp/Store.png.meta
  BloodStore/Assets/Sprite/PT_temp/arrow.png.meta
  BloodStore/Assets/Sprite/PT_temp/button.png.meta
  BloodStore/Assets/Sprite/PT_temp/button_light.png.meta
  BloodStore/Assets/Sprite/PT_temp/button_light_noback.png.meta
  BloodStore/Assets/Sprite/PT_temp/cha1.png.meta
  BloodStore/Assets/Sprite/PT_temp/cha2.png.meta
  BloodStore/Assets/Sprite/PT_temp/frame_blood.png.meta
  BloodStore/Assets/Sprite/PT_temp/frame_normal.png.meta
  BloodStore/Assets/Sprite/PT_temp/frame_null.png.meta
  BloodStore/Assets/Sprite/PT_temp/frame_select.png.meta
  BloodStore/Assets/Sprite/PT_temp/frame_white.png
  BloodStore/Assets/Sprite/PT_temp/frame_white.png.meta
  BloodStore/Assets/Sprite/PT_temp/kitchen.png.meta
  BloodStore/Assets/Sprite/PT_temp/noback.png.meta
  BloodStore/Assets/Sprite/PT_temp/paper.png.meta
  BloodStore/Assets/Sprite/PT_temp/resultFT.png.meta
  BloodStore/Assets/Sprite/PT_temp/resultST.png.meta
  BloodStore/Assets/Sprite/PT_temp/selectCardUI_background.png.meta
  BloodStore/Assets/Sprite/PT_temp/selectCardUI_frame1.png.meta
  BloodStore/Assets/Sprite/PT_temp/selectCardUI_frame2.png.meta
  BloodStore/Assets/Sprite/PT_temp/selectCardUI_frame3.png.meta
  BloodStore/Assets/Sprite/PT_temp/selectCardUI_frame4.png.meta
  BloodStore/Assets/Sprite/PT_temp/selectCardUI_frame5.png.meta
  BloodStore/Assets/Sprite/PT_temp/selectCardUI_sealingwax.png.meta
  BloodStore/Assets/Sprite/PT_temp/ui_line1.png.meta
  BloodStore/Assets/Sprite/PT_temp/ui_line2.png.meta
  BloodStore/Assets/Sprite/PT_temp/ui_line_head.png.meta
Labels: style

#352 [style] : for merge
  BloodStore/Assets/Sprite/PT_temp/paper.png.meta
Labels: style

#353 upload
  BloodStore/Assets/Prefab/DeadNode.prefab
  BloodStore/Assets/Prefab/EmptyNode.prefab
  BloodStore/Assets/Prefab/Highlight.prefab
  BloodStore/Assets/Prefab/Node.prefab
  BloodStore/Assets/Scenes/FamilyTree.unity
  BloodStore/Assets/Scenes/ResultFamilyTree.unity
  BloodStore/Assets/Scripts/GameManager/ImageLoad.cs
  BloodStore/Assets/Scripts/UI/DayUI/DayShowing.cs
  BloodStore/Assets/Scripts/UI/ResultFamilyTree/ResultMoney.cs
  BloodStore/Assets/Scripts/UI/SelectableCardUI/SelectableCardDisplay.cs
  BloodStore/Assets/Scripts/UI/SelectableCardUI/SelectedCardDisplay.cs
  BloodStore/Assets/Sprite/PT_temp/frame_select.png.meta
Labels: style

#354 [style] <ResultFamilyTree> : complete Save UI design apply
  BloodStore/Assets/Scenes/ResultFamilyTree.unity
  BloodStore/Assets/TextMesh Pro/Resources/Fonts & Materials/LiberationSans SDF - Fallback.asset
Labels: style

#356 [style] <Start> <StartMenu> <ResultStore> <LoadStatus> : change Scene…
  BloodStore/Assets/Scenes/LoadStatus.unity
  BloodStore/Assets/Scenes/ResultFamilyTree.unity
  BloodStore/Assets/Scenes/ResultStore.unity
  BloodStore/Assets/Scenes/Start.unity
  BloodStore/Assets/Scenes/StartMenu.unity
  BloodStore/Assets/Scripts/SO/FamilyTreeSO/FemaleProfileImageSO.asset
  BloodStore/Assets/Scripts/SO/FamilyTreeSO/MaleProfileImageSO.asset
  BloodStore/Assets/Scripts/UI/LoadStatus/SetBackground.cs
  BloodStore/Assets/Scripts/UI/LoadStatus/SetBackground.cs.meta
  BloodStore/Assets/Sprite/PT_temp/profiles.meta
  BloodStore/Assets/Sprite/PT_temp/profiles/female.meta
  BloodStore/Assets/Sprite/PT_temp/profiles/female/10.png
  BloodStore/Assets/Sprite/PT_temp/profiles/female/10.png.meta
  BloodStore/Assets/Sprite/PT_temp/profiles/female/11.png
  BloodStore/Assets/Sprite/PT_temp/profiles/female/11.png.meta
  BloodStore/Assets/Sprite/PT_temp/profiles/female/13.png
  BloodStore/Assets/Sprite/PT_temp/profiles/female/13.png.meta
  BloodStore/Assets/Sprite/PT_temp/profiles/female/16.png
  BloodStore/Assets/Sprite/PT_temp/profiles/female/16.png.meta
  BloodStore/Assets/Sprite/PT_temp/profiles/female/2.png
  BloodStore/Assets/Sprite/PT_temp/profiles/female/2.png.meta
  BloodStore/Assets/Sprite/PT_temp/profiles/female/3.png
  BloodStore/Assets/Sprite/PT_temp/profiles/female/3.png.meta
  BloodStore/Assets/Sprite/PT_temp/profiles/female/7.png
  BloodStore/Assets/Sprite/PT_temp/profiles/female/7.png.meta
  BloodStore/Assets/Sprite/PT_temp/profiles/male.meta
  BloodStore/Assets/Sprite/PT_temp/profiles/male/1.png
  BloodStore/Assets/Sprite/PT_temp/profiles/male/1.png.meta
  BloodStore/Assets/Sprite/PT_temp/profiles/male/12.png
  BloodStore/Assets/Sprite/PT_temp/profiles/male/12.png.meta
  BloodStore/Assets/Sprite/PT_temp/profiles/male/14.png
  BloodStore/Assets/Sprite/PT_temp/profiles/male/14.png.meta
  BloodStore/Assets/Sprite/PT_temp/profiles/male/15.png
  BloodStore/Assets/Sprite/PT_temp/profiles/male/15.png.meta
  BloodStore/Assets/Sprite/PT_temp/profiles/male/17.png
  BloodStore/Assets/Sprite/PT_temp/profiles/male/17.png.meta
  BloodStore/Assets/Sprite/PT_temp/profiles/male/18.png
  BloodStore/Assets/Sprite/PT_temp/profiles/male/18.png.meta
  BloodStore/Assets/Sprite/PT_temp/profiles/male/4.png
  BloodStore/Assets/Sprite/PT_temp/profiles/male/4.png.meta
  BloodStore/Assets/Sprite/PT_temp/profiles/male/5.png
  BloodStore/Assets/Sprite/PT_temp/profiles/male/5.png.meta
  BloodStore/Assets/Sprite/PT_temp/profiles/male/6.png
  BloodStore/Assets/Sprite/PT_temp/profiles/male/6.png.meta
  BloodStore/Assets/Sprite/PT_temp/profiles/male/8.png
  BloodStore/Assets/Sprite/PT_temp/profiles/male/8.png.meta
  BloodStore/Assets/Sprite/PT_temp/profiles/male/9.png
  BloodStore/Assets/Sprite/PT_temp/profiles/male/9.png.meta
Labels: style

#359 [fix] SaveUI.cs : fix the select arrow exist error
  BloodStore/Assets/Scripts/UI/SaveUI/SaveUI.cs
Labels: fix
