Repository unhappy1030/BloodStore, pull requests merged in 2024-02, with the labels that each got.

#129 Fix/#115
  BloodStore/Assets/BloodPack.json
  BloodStore/Assets/FamilyTree.json
  BloodStore/Assets/Scenes/Edit.unity
  BloodStore/Assets/Scripts/LeeUlim/Control/CameraControl.cs
  BloodStore/Assets/Scripts/LeeUlim/NodeInteraction.cs
Labels: fix

#131 Feat/#98
  BloodStore/Assets/BloodPack.json
  BloodStore/Assets/FamilyTree.json
  BloodStore/Assets/Scripts/LeeUlim/Dialogue/DialogueControl.cs
  BloodStore/Assets/Scripts/LeeUlim/Dialogue/NPCInteract.cs
  BloodStore/Assets/Scripts/LeeUlim/Dialogue/YarnControl.cs
  BloodStore/Assets/YarnSpinner/Customer/test/Npc/NormalNPC.yarn
Labels: feat

#140 [style] <Test1> : add svg package
  BloodStore/Assets/Sprite/svg.meta
  BloodStore/Assets/Sprite/svg/Card_Background (1).svg
  BloodStore/Assets/Sprite/svg/Card_Background (1).svg.meta
  BloodStore/Assets/Sprite/svg/Card_Background (2).svg
  BloodStore/Assets/Sprite/svg/Card_Background (2).svg.meta
  BloodStore/Assets/Sprite/svg/Card_Background.svg
  BloodStore/Assets/Sprite/svg/Card_Background.svg.meta
  BloodStore/Assets/Sprite/svg/fillNode (2).svg
  BloodStore/Assets/Sprite/svg/fillNode (2).svg.meta
  BloodStore/Assets/Sprite/svg/fillNode.svg
  BloodStore/Assets/Sprite/svg/fillNode.svg.meta
  BloodStore/Packages/manifest.json
  BloodStore/Packages/packages-lock.json
Labels: style

#142 Fix/#141
  BloodStore/Assets/Scripts/LeeUlim/Control/CameraControl.cs
  BloodStore/Assets/Scripts/LeeUlim/NodeInteraction.cs
Labels: fix

#149 Feat/#133
  BloodStore/Assets/Scenes/Test.unity
  BloodStore/Assets/Scripts/GameManager/BloodPacks.cs
  BloodStore/Assets/Scripts/NPC/YarnControl.cs
  BloodStore/Assets/Scripts/UI/BloodPackUI/BloodPackCount.cs
  BloodStore/Assets/Scripts/UI/BloodPackUI/BloodPackUITest.cs
  BloodStore/Assets/YarnSpinner/Customer/test/Npc/NormalNPC.yarn
Labels: feat

#153 Feat/#133
  BloodStore/Assets/Scenes/Store.unity
  BloodStore/Assets/Scenes/Test.unity
  BloodStore/Assets/Scripts/NPC/NPCInteract.cs
  BloodStore/Assets/Scripts/UI/BloodPackUI/BloodPackUITest.cs
  BloodStore/Assets/Sprite/BetaDesign/170D.png.meta
  BloodStore/Assets/Sprite/BetaDesign/180D.png.meta
  BloodStore/Assets/Sprite/BetaDesign/270D.png.meta
  BloodStore/Assets/Sprite/BetaDesign/300_420D.png.meta
  BloodStore/Assets/Sprite/BetaDesign/300x420.png.meta
  BloodStore/Assets/Sprite/BetaDesign/KakaoTalk_20240122_042644225.png.meta
  BloodStore/Assets/Sprite/BetaDesign/KakaoTalk_20240122_042644225_01.png.meta
  BloodStore/Assets/Sprite/BetaDesign/KakaoTalk_20240122_042644225_03.png.meta
  BloodStore/Assets/Sprite/BetaDesign/Node.png.meta
  BloodStore/Assets/Sprite/BetaDesign/button 20.png.meta
  BloodStore/Assets/Sprite/BetaDesign/button_ori.png.meta
  BloodStore/Assets/Sprite/BetaDesign/fillNode_180.png.meta
  BloodStore/Assets/Sprite/BetaDesign/text.png.meta
  BloodStore/Assets/Sprite/BetaDesign/text_ori.png.meta
  BloodStore/Assets/YarnSpinner/Customer/test/Npc/NormalNPC.yarn
Labels: feat

#156 Enhance/#154
  BloodStore/Assets/Scripts/CameraControl/CameraControl.cs
  BloodStore/Assets/Scripts/FamilyTree/NodeInteraction.cs
  BloodStore/Assets/Scripts/GameManager/GameManager.cs
  BloodStore/Assets/Scripts/NPC/NPCInteract.cs
  BloodStore/Assets/Scripts/NPC/YarnControl.cs
  BloodStore/Assets/YarnSpinner/Customer/test/Npc/NormalNPC.yarn
Labels: enhance

#159 Enhance/#158
  BloodStore/Assets/Scenes/Store.unity
  BloodStore/Assets/Scripts/GameManager/MouseRayCast.cs
  BloodStore/Assets/Scripts/MouseInput/InteractObjInfo.cs
  BloodStore/Assets/YarnSpinner/Customer/test/Npc/NormalNPC.yarn
  mintty.2024-02-05_15-42-36.png
Labels: enhance

#160 Enhance/#157
  BloodStore/Assets/Scenes/Store.unity
  BloodStore/Assets/Scripts/GameManager/MouseRayCast.cs
  BloodStore/Assets/Scripts/NPC/NPCInteract.cs
  BloodStore/Assets/Scripts/NPC/YarnControl.cs
  BloodStore/Assets/Scripts/UI/BloodPackUI/BloodPackUITest.cs
  BloodStore/Assets/Scripts/UI/BloodPackUI/ChangeSelected.cs
  BloodStore/Assets/YarnSpinner/Customer/test/CustomerDialogue.yarn
  BloodStore/Assets/YarnSpinner/Customer/test/Npc/NormalNPC.yarn
Labels: enhance

#162 [feat] : UIControl - add pasue() & escapePause()
  BloodStore/Assets/Scripts/FamilyTree/NodeInteraction.cs
  BloodStore/Assets/Scripts/GameManager/MouseRayCast.cs
  BloodStore/Assets/Scripts/GameManager/UIControl.cs
  BloodStore/Assets/Scripts/NPC/NPCInteract.cs
  BloodStore/Assets/Scripts/UI/BloodPackUI/BloodPackUITest.cs
Labels: feat

#164 [test] <Start> : 'DialogueAdvanceInput' component checked but not app…
  BloodStore/Assets/Scenes/Start.unity
  BloodStore/Assets/Sprite/tempImage/TextBox.png.meta
Labels: test

#167 [fix] : add EscapePause method in 'nothing' status
  BloodStore/Assets/Scripts/GameManager/UIControl.cs
Labels: fix

#173 Feat/#165
  BloodStore/Assets/Scenes/Start.unity
  BloodStore/Assets/Scripts/GameManager/DialogueControl.cs
  BloodStore/Assets/Scripts/NPC/NPCInteract.cs
  BloodStore/Assets/Scripts/NPC/YarnControl.cs
  BloodStore/Assets/Scripts/SO/DialogueSO/BloodTasteSO.cs
  BloodStore/Assets/Scripts/SO/DialogueSO/SOstore/Taste/BloodType.asset
  BloodStore/Assets/Scripts/SO/DialogueSO/SOstore/Taste/BloodType.asset.meta
  BloodStore/Assets/Scripts/SO/DialogueSO/SOstore/Taste/Rh.asset
  BloodStore/Assets/Scripts/SO/DialogueSO/SOstore/Taste/Sex.asset
  BloodStore/Assets/Scripts/SO/DialogueSO/SOstore/Taste/Sex.asset.meta
  BloodStore/Assets/YarnSpinner/Customer/test/Npc/NormalNPC.yarn
Labels: feat

#180 Style/#174
  BloodStore/Assets/Animation.meta
  BloodStore/Assets/Animation/Animation.meta
  BloodStore/Assets/Animation/Animation/Background.anim
  BloodStore/Assets/Animation/Animation/Background.anim.meta
  BloodStore/Assets/Animation/Animation/Castle.anim
  BloodStore/Assets/Animation/Animation/Castle.anim.meta
  BloodStore/Assets/Animation/Animation/Ground.anim
  BloodStore/Assets/Animation/Animation/Ground.anim.meta
  BloodStore/Assets/Animation/Animation/Wall.anim
  BloodStore/Assets/Animation/Animation/Wall.anim.meta
  BloodStore/Assets/Animation/Animator.meta
  BloodStore/Assets/Animation/Animator/Background.controller
  BloodStore/Assets/Animation/Animator/Background.controller.meta
  BloodStore/Assets/Animation/Animator/Castle.controller
  BloodStore/Assets/Animation/Animator/Castle.controller.meta
  BloodStore/Assets/Animation/Animator/Ground.controller
  BloodStore/Assets/Animation/Animator/Ground.controller.meta
  BloodStore/Assets/Animation/Animator/Wall.controller
  BloodStore/Assets/Animation/Animator/Wall.controller.meta
  BloodStore/Assets/Scenes/ChangeStartDesign.unity
  BloodStore/Assets/Scenes/ChangeStartDesign.unity.meta
  BloodStore/Assets/Scenes/Start.unity
  BloodStore/Assets/Scripts/UI/StartSceneUI.meta
  BloodStore/Assets/Scripts/UI/StartSceneUI/StartScene.cs
  BloodStore/Assets/Scripts/UI/StartSceneUI/StartScene.cs.meta
  BloodStore/Assets/Sprite/BetaDesign/Title.png
  BloodStore/Assets/Sprite/BetaDesign/Title.png.meta
  BloodStore/Assets/Sprite/BetaDesign/castle.png
  BloodStore/Assets/Sprite/BetaDesign/castle.png.meta
  BloodStore/Assets/Sprite/BetaDesign/start_background.png
  BloodStore/Assets/Sprite/BetaDesign/start_background.png.meta
  BloodStore/Assets/Sprite/BetaDesign/wall.png
  BloodStore/Assets/Sprite/BetaDesign/wall.png.meta
Labels: style

#182 Feat/#181
  BloodStore/Assets/Scripts/FamilyTree/NodeInteraction.cs
Labels: feat

#185 [feat] : NodeInteraction - block camera move if camera position doesn…
  BloodStore/Assets/Scripts/FamilyTree/NodeInteraction.cs
Labels: feat

#193 Feat/#189
  BloodStore/Assets/Scenes/Store.unity
  BloodStore/Assets/Scripts/NPC/BloodFiltering.cs
  BloodStore/Assets/Scripts/NPC/BloodFiltering.cs.meta
  BloodStore/Assets/Scripts/NPC/BloodSellProcess.cs
  BloodStore/Assets/Scripts/NPC/BloodSellProcess.cs.meta
  BloodStore/Assets/Scripts/NPC/NPCInteract.cs
  BloodStore/Assets/Scripts/NPC/YarnControl.cs
  BloodStore/Assets/Scripts/UI/BloodPackUI/BloodPackUITest.cs
  BloodStore/Assets/Sprite/BetaDesign/Title.png.meta
  BloodStore/Assets/YarnSpinner/Customer/test/Npc/NormalNPC.yarn
Labels: feat

#200 [enhance] <Start> & <StartMenu> : separate start scene with animation…
  BloodStore/Assets/Animation/Animator/Background.controller
  BloodStore/Assets/Scenes/Start.unity
  BloodStore/Assets/Scenes/StartMenu.unity
  BloodStore/Assets/Scenes/StartMenu.unity.meta
  BloodStore/Assets/Scripts/UI/StartSceneUI/StartScene.cs
  BloodStore/ProjectSettings/EditorBuildSettings.asset
Labels: enhance

#204 [feat] <ResultStore> : Show result of store, GameManager & MoneyContr…
  BloodStore/Assets/Scenes/ResultStore.unity
  BloodStore/Assets/Scripts/GameManager/GameManager.cs
  BloodStore/Assets/Scripts/GameManager/MoneyControl.cs
  BloodStore/Assets/Scripts/UI/ResultStoreUI.meta
  BloodStore/Assets/Scripts/UI/ResultStoreUI/ResultStore.cs
  BloodStore/Assets/Scripts/UI/ResultStoreUI/ResultStore.cs.meta
  BloodStore/Assets/YarnSpinner/Customer/test/Npc/NormalNPC.yarn
Labels: feat

#207 [feat] : BloodSellProcess - Apply blood pack subtraction
  BloodStore/Assets/Scripts/NPC/BloodSellProcess.cs
Labels: feat

#210 [fix] <FamilyTree> : Fix EmptyDisplay ChangeDisplay Method Make BoxCo…
  BloodStore/Assets/Scripts/FamilyTree/EmptyDisplay.cs
Labels: fix

#212 [fix] <FamilyTree> : Group Script - Line Part and Highlight fixed
  BloodStore/Assets/Prefab/EmptyNode.prefab
  BloodStore/Assets/Prefab/Highlight.prefab
  BloodStore/Assets/Prefab/Node.prefab
  BloodStore/Assets/Scripts/FamilyTree/Group.cs
Labels: fix

#213 Enhance/#208
  BloodStore/Assets/Scenes/Store.unity
  BloodStore/Assets/Scripts/NPC/BloodSellProcess.cs
Labels: enhance

#215 [enhance] : block selecting blood pack when there is not selected type
  BloodStore/Assets/Scripts/UI/BloodPackUI/BloodPackUITest.cs
Labels: feat

#220 [feat] <FamilyTree> : Make indepent AddChildUI Value in each Pair
  BloodStore/Assets/Scenes/Start.unity
  BloodStore/Assets/Scripts/FamilyTree/Group.cs
  BloodStore/Assets/Scripts/FamilyTree/TreeManager.cs
  BloodStore/Assets/Scripts/UI/AddChildUI/ChildAddUI.cs
  BloodStore/Assets/Scripts/UI/AddChildUI/ValueButton.cs
Labels: feat

#222 Fix/#219
  BloodStore/Assets/Scenes/Store.unity
  BloodStore/Assets/Scripts/GameManager/BloodPacks.cs
  BloodStore/Assets/Scripts/NPC/BloodSellProcess.cs
Labels: fix

#223 [feat] <FamilyTree> : Make DataBase For AddChild Button Contents and …
  BloodStore/Assets/Scenes/FamilyTree.unity
  BloodStore/Assets/Scripts/FamilyTree/Group.cs
  BloodStore/Assets/Scripts/FamilyTree/Group.cs.meta
  BloodStore/Assets/Scripts/FamilyTree/TreeManager.cs
  BloodStore/Assets/Scripts/GameManager/BloodPacks.cs
  BloodStore/Assets/Scripts/SO/FamilyTreeSO/AddChildSO.asset
  BloodStore/Assets/Scripts/SO/FamilyTreeSO/AddChildSO.asset.meta
  BloodStore/Assets/Scripts/SO/FamilyTreeSO/AddChildSO.cs
  BloodStore/Assets/Scripts/SO/FamilyTreeSO/AddChildSO.cs.meta
  BloodStore/Assets/Scripts/UI/AddChildUI/ChildAddUI.cs
  BloodStore/Assets/Scripts/UI/AddChildUI/ValueButton.cs
Labels: feat

#225 [fix] Group : SetValues Method fixed, Not select same idx by check ad…
  BloodStore/Assets/Scripts/FamilyTree/Group.cs
Labels: fix

#227 [feat] Pairs : Make Limit of ChildNUM(5) complete
  BloodStore/Assets/Scripts/GameManager/Pairs.cs
  BloodStore/Assets/Scripts/SO/FamilyTreeSO/AddChildSO.asset
Labels: feat

#229 Enhance/#216
  BloodStore/Assets/Scenes/ResultStore.unity
  BloodStore/Assets/Scenes/Store.unity
  BloodStore/Assets/Scripts/GameManager/DialogueControl.cs
  BloodStore/Assets/Scripts/GameManager/GameManager.cs
  BloodStore/Assets/Scripts/NPC/BloodSellProcess.cs
  BloodStore/Assets/Scripts/NPC/NPCInteract.cs
  BloodStore/Assets/Scripts/UI/ResultStoreUI/ResultStore.cs
Labels: enhance

#231 [teat] : DialogueControl - find that only words are showed -> fix pro…
  BloodStore/Assets/Scripts/GameManager/DialogueControl.cs
Labels: test

#233 [fix] TreeManager : fix MakeOlder Method procedure order and overlapp…
  BloodStore/Assets/Scripts/FamilyTree/TreeManager.cs
  BloodStore/Assets/Scripts/UI/PackingUI/PackingUI.cs
Labels: fix

#235 [fix] BloodPacks.cs, ResultBloodPack.cs : fix rubbish ResultFamilyTre…
  BloodStore/Assets/Prefab/DeadNode.prefab
  BloodStore/Assets/Scripts/GameManager/BloodPacks.cs
  BloodStore/Assets/Scripts/UI/ResultFamilyTree/ResultBloodPack.cs
Labels: fix

#237 [fix] SelectableCardGroup.cs : Fix Cardlist(List<GameObject>) add Ini…
  BloodStore/Assets/Scripts/UI/SelectableCardUI/SelectableCardGroup.cs
Labels: fix

#239 Enhance/#232
  BloodStore/Assets/Scripts/GameManager/DialogueControl.cs
  BloodStore/Assets/Scripts/SO/DialogueSO/BloodTasteSO.cs
Labels: enhance

#240 Feat/#183
  BloodStore/Assets/Scenes/FamilyTree.unity
  BloodStore/Assets/Scenes/ResultFamilyTree.unity
  BloodStore/Assets/Scenes/ResultStore.unity
  BloodStore/Assets/Scenes/Start.unity
  BloodStore/Assets/Scenes/StartMenu.unity
  BloodStore/Assets/Scenes/Store.unity
  BloodStore/Assets/Scripts/CameraControl/SetScreenSize.cs
  BloodStore/Assets/Scripts/CameraControl/SetScreenSize.cs.meta
  BloodStore/Assets/Scripts/SO/DialogueSO/SOstore/Taste/BloodType.asset
  BloodStore/Assets/Scripts/SO/DialogueSO/SOstore/Taste/Rh.asset
  BloodStore/Assets/Scripts/SO/DialogueSO/SOstore/Taste/Sex.asset
  BloodStore/ProjectSettings/ProjectSettings.asset
Labels: feat

#246 [fix] Fix CameraZoom Error complete
  BloodStore/Assets/Scripts/FamilyTree/NodeInteraction.cs
Labels: fix

#248 Enhance/#241
  BloodStore/Assets/Scenes/Store.unity
  BloodStore/Assets/Scripts/GameManager/GameManager.cs
  BloodStore/Assets/Scripts/NPC/BloodSellProcess.cs
  BloodStore/Assets/Scripts/NPC/NPCInteract.cs
  BloodStore/Assets/Scripts/NPC/YarnControl.cs
  BloodStore/Assets/YarnSpinner/Customer/test/Npc/NormalNPC.yarn
Labels: enhance

#250 [feat] Make Auto Save complete
  BloodStore/Assets/Scripts/GameManager/GameManager.cs
  BloodStore/Assets/Scripts/UI/PackingUI/PackingUI.cs
  BloodStore/Assets/Scripts/UI/SaveFileSelectUI/SaveFileSelectUI.cs
Labels: feat

#252 [fix] Fix BloodPack Subtraction Method : Apply Subtraction Method, Ad…
  BloodStore/Assets/Scenes/Store.unity
  BloodStore/Assets/Scripts/NPC/BloodSellProcess.cs
  BloodStore/Assets/Scripts/UI/BloodPackUI/BloodPackCount.cs
  BloodStore/Assets/Scripts/UI/PackingUI/PackingUI.cs
  BloodStore/Assets/Scripts/UI/ResultFamilyTree/ResultBloodPack.cs
Labels: fix

#253 [feat] Organize mouse input for multiple collider : Set FirstSibliing…
  BloodStore/Assets/Scripts/FamilyTree/EmptyDisplay.cs
  BloodStore/Assets/Scripts/FamilyTree/Group.cs
  BloodStore/Assets/Sprite/BetaDesign/button_ori.png.meta
Labels: feat

#255 [fix] Fix Save File Part : BloodPack Load Error fix complete
  BloodStore/Assets/Scripts/GameManager/BloodPacks.cs
  BloodStore/Assets/Scripts/UI/StartSceneUI/StartScene.cs
Labels: fix

#258 Feat/#257
  BloodStore/Assets/Scenes/SecretPlace.unity
  BloodStore/Assets/Scenes/Start.unity
  BloodStore/Assets/Scenes/StartMenu.unity
  BloodStore/Assets/Scripts/UI/LoadUI.meta
  BloodStore/Assets/Scripts/UI/LoadUI/LoadUI.cs
  BloodStore/Assets/Scripts/UI/LoadUI/LoadUI.cs.meta
  BloodStore/Assets/Scripts/UI/SaveFileSelectUI/SaveFileSelectUI.cs
Labels: feat

#260 [feat] Modify SaveUI Procedure in ResultFamilyTree and ResultStore Sc…
  BloodStore/Assets/Scenes/ResultFamilyTree.unity
  BloodStore/Assets/Scenes/ResultStore.unity
  BloodStore/Assets/Scenes/SecretPlace.unity
  BloodStore/Assets/Scenes/Start.unity
  BloodStore/Assets/Scenes/StartMenu.unity
  BloodStore/Assets/Scripts/UI/PackingUI/PackingUI.cs
  BloodStore/Assets/Scripts/UI/SaveUI/SaveUI.cs
Labels: feat

#262 [feat] Mark selected file with cursor
  BloodStore/Assets/Scenes/ResultFamilyTree.unity
  BloodStore/Assets/Scenes/ResultStore.unity
  BloodStore/Assets/Scenes/SecretPlace.unity
  BloodStore/Assets/Scenes/Start.unity
  BloodStore/Assets/Scenes/StartMenu.unity
  BloodStore/Assets/Scripts/UI/SaveUI/SaveUI.cs
Labels: feat

#266 Feat/#256
  BloodStore/Assets/Scenes/Start.unity
  BloodStore/Assets/Scenes/Store.unity
  BloodStore/Assets/Scenes/Test.unity
  BloodStore/Assets/Scripts/FamilyTree/NodeInteraction.cs
  BloodStore/Assets/Scripts/GameManager/DialogueControl.cs
  BloodStore/Assets/Scripts/GameManager/GameManager.cs
  BloodStore/Assets/Scripts/GameManager/MouseRayCast.cs
  BloodStore/Assets/Scripts/GameManager/Tutorial.cs
  BloodStore/Assets/Scripts/GameManager/Tutorial.cs.meta
  BloodStore/Assets/Scripts/NPC/NPCInteract.cs
  BloodStore/Assets/Scripts/NPC/YarnControl.cs
  BloodStore/Assets/Scripts/SO/DialogueSO/NPCSO.cs
  BloodStore/Assets/Scripts/SO/DialogueSO/SOstore/NPC/NPC1SO.asset
  BloodStore/Assets/Scripts/SO/DialogueSO/SOstore/NPC/NPC2SO.asset
Labels: feat

#268 Feat/#265
  BloodStore/Assets/Scenes/ResultFamilyTree.unity
  BloodStore/Assets/Scenes/ResultStore.unity
  BloodStore/Assets/Scenes/SecretPlace.unity
  BloodStore/Assets/Scenes/Start.unity
  BloodStore/Assets/Scenes/StartMenu.unity
  BloodStore/Assets/Scripts/FamilyTree/TreeManager.cs
  BloodStore/Assets/Scripts/GameManager/BloodPacks.cs
  BloodStore/Assets/Scripts/GameManager/Pairs.cs
  BloodStore/Assets/Scripts/UI/LoadUI/LoadUI.cs
  BloodStore/Assets/Scripts/UI/SaveUI/SaveUI.cs
  BloodStore/Assets/Scripts/UI/StartSceneUI/StartScene.cs
Labels: feat

#270 [feat] Add Total Cost View on PackingUI
  BloodStore/Assets/Scenes/FamilyTree.unity
  BloodStore/Assets/Scripts/UI/PackingUI/PackingUI.cs
Labels: feat

#272 [fix] Fix Subtraction BloodPack Error : Last one BloodPack Condition …
  BloodStore/Assets/Scripts/GameManager/BloodPacks.cs
Labels: fix

#274 [fix] Fix PackingUI Cost Error : if year == 0, totalcost == 0
  BloodStore/Assets/Scripts/UI/PackingUI/PackingUI.cs
Labels: fix

#275 Fix/#267
  BloodStore/Assets/Scripts/FamilyTree/NodeInteraction.cs
Labels: fix

#277 [feat] <FamilyTree> <ResultStore> <ResultFamilyTree> <Start> <StartMe…
  BloodStore/Assets/Scenes/FamilyTree.unity
  BloodStore/Assets/Scenes/ResultFamilyTree.unity
  BloodStore/Assets/Scenes/ResultStore.unity
  BloodStore/Assets/Scenes/Start.unity
  BloodStore/Assets/Scenes/StartMenu.unity
Labels: feat

#280 [feat] <ResultFamilyTree> <ResultStore> : DayShowing - add day show s…
  BloodStore/Assets/Scenes/ResultFamilyTree.unity
  BloodStore/Assets/Scenes/ResultStore.unity
  BloodStore/Assets/Scripts/UI/DayUI.meta
  BloodStore/Assets/Scripts/UI/DayUI/DayShowing.cs
  BloodStore/Assets/Scripts/UI/DayUI/DayShowing.cs.meta
Labels: feat

#288 Enhance/#285
  BloodStore/Assets/Scenes/FamilyTree.unity
  BloodStore/Assets/Scenes/ResultFamilyTree.unity
  BloodStore/Assets/Scenes/ResultStore.unity
  BloodStore/Assets/Scenes/Start.unity
  BloodStore/Assets/Scenes/StartMenu.unity
  BloodStore/Assets/Scenes/Store.unity
  BloodStore/ProjectSettings/TagManager.asset
Labels: enhance

#290 [fix] : UIControl - set status as None when in StartMenu scene
  BloodStore/Assets/Scripts/GameManager/UIControl.cs
Labels: fix

#293 [feat] <FamilyTree> : Add Panel on noticeUI, CheckPairUI
  BloodStore/Assets/Scenes/FamilyTree.unity
Labels: feat

#296 Enhance/#291
  BloodStore/Assets/Scripts/GameManager/GameManager.cs
  BloodStore/Assets/Scripts/GameManager/MouseRayCast.cs
  BloodStore/Assets/Scripts/NPC/NPCInteract.cs
  BloodStore/Assets/Scripts/UI/ButtonControl.cs
  BloodStore/Assets/Scripts/UI/LoadStatus/StatusNextScene.cs
  BloodStore/Assets/Scripts/UI/StartSceneUI/StartScene.cs
Labels: enhance

#298 Feat/#297
  BloodStore/Assets/Scenes/FamilyTree.unity
  BloodStore/Assets/Scenes/ResultFamilyTree.unity
  BloodStore/Assets/Scenes/ResultStore.unity
  BloodStore/Assets/Scenes/Start.unity
  BloodStore/Assets/Scenes/StartMenu.unity
  BloodStore/Assets/Scenes/Store.unity
  BloodStore/Assets/Scripts/GameManager/GameManager.cs
  BloodStore/Assets/Scripts/GameManager/Tutorial.cs
  BloodStore/Assets/Scripts/GameManager/TutorialControl.cs
  BloodStore/Assets/Scripts/GameManager/TutorialControl.cs.meta
  BloodStore/Assets/Scripts/GameManager/UIControl.cs
  BloodStore/Assets/Scripts/UI/StartSceneUI/StartScene.cs
Labels: feat

#300 [feat] StartScene.cs, SaveData.cs : Set NewGame Initialize GameManger…
  BloodStore/Assets/Scripts/GameManager/SaveData.cs
  BloodStore/Assets/Scripts/UI/StartSceneUI/StartScene.cs
Labels: feat

#301 [feat] <Store> : Make Ending Scene and Condition for Ending Scene Loa…
  BloodStore/Assets/Scenes/Ending1.unity
  BloodStore/Assets/Scenes/Ending1.unity.meta
  BloodStore/Assets/Scenes/Store.unity
  BloodStore/Assets/Scripts/UI/ButtonControl.cs
  BloodStore/Assets/Scripts/UI/StoreCanvasUI.meta
  BloodStore/Assets/Scripts/UI/StoreCanvasUI/EndingSceneCheck.cs
  BloodStore/Assets/Scripts/UI/StoreCanvasUI/EndingSceneCheck.cs.meta
  BloodStore/ProjectSettings/EditorBuildSettings.asset
Labels: feat

#303 Fix/#302
  BloodStore/Assets/Scripts/GameManager/DialogueControl.cs
Labels: fix

#305 [fix] <FamilyTree> : Delete setActive Script Part On UIs
  BloodStore/Assets/Scenes/FamilyTree.unity
  BloodStore/Assets/Scripts/UI/UIOffButton.cs
  BloodStore/Assets/Scripts/UI/UIOffButton.cs.meta
  BloodStore/Assets/Scripts/UI/UIOnButton.cs
  BloodStore/Assets/Scripts/UI/UIOnButton.cs.meta
Labels: fix

#307 [fix] <FamilyTree> : Fix NodeInteraction Collider Error
  BloodStore/Assets/Scripts/FamilyTree/NodeInteraction.cs
Labels: fix

#309 Fix/#308
  BloodStore/Assets/Scenes/FamilyTree.unity
Labels: fix

#311 [feat] <FamilyTree> : Add EndingUI for FamilyTree All People Dead Case
  BloodStore/Assets/Scenes/AllDeadEnding.unity
  BloodStore/Assets/Scenes/AllDeadEnding.unity.meta
  BloodStore/Assets/Scenes/FamilyTree.unity
  BloodStore/Assets/Scenes/SecretPlace.unity
  BloodStore/Assets/Scenes/Start.unity
  BloodStore/Assets/Scripts/GameManager/Pairs.cs
  BloodStore/Assets/Scripts/UI/EndingUI.meta
  BloodStore/Assets/Scripts/UI/EndingUI/AllDeadEndingUI.cs
  BloodStore/Assets/Scripts/UI/EndingUI/AllDeadEndingUI.cs.meta
  BloodStore/ProjectSettings/EditorBuildSettings.asset
Labels: feat

#312 Feat/#297
  BloodStore/Assets/Scenes/FamilyTree.unity
  BloodStore/Assets/Scenes/Start.unity
  BloodStore/Assets/Scenes/Store.unity
  BloodStore/Assets/Scripts/FamilyTree/NodeInteraction.cs
  BloodStore/Assets/Scripts/GameManager/GameManager.cs
  BloodStore/Assets/Scripts/GameManager/Tutorial.cs
  BloodStore/Assets/Scripts/GameManager/TutorialControl.cs
  BloodStore/Assets/Scripts/GameManager/UIControl.cs
  BloodStore/Assets/Scripts/NPC/NPCInteract.cs
  BloodStore/Assets/Scripts/UI/StartSceneUI/StartScene.cs
Labels: feat

#314 [feat] : GameManager - fix error & NPCInteract - change fade time
  BloodStore/Assets/Scripts/GameManager/GameManager.cs
  BloodStore/Assets/Scripts/NPC/NPCInteract.cs
Labels: fix

#316 [enhance] <Start> : change dialogue pannel to button
  BloodStore/Assets/Scenes/Start.unity
Labels: enhance

#318 [fix] <Start> : add pannel in dialogue System
  BloodStore/Assets/Scenes/Start.unity
Labels: fix
